version: '3.8'

services:
  # Base de datos PostgreSQL para desarrollo
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  # Backend API para desarrollo
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:5175
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend para desarrollo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5175:5175"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_dev_data: 